### ISSUE TITLE
issue with resuming training examples

### ISSUE THREAD

**Issue by anadb** [Xilinx/brevitas#126]
When I tried to resume example training with command 
`PYTORCH_JIT=1 brevitas_bnn_pynq_train --network CNV_2W2A --experiments ./TrainedModels/ --gpus None --epochs 10 --resume /TrainedModels/ ... /checkpoint.tar
`
I got an error 

`  File "/home/anatoly/.local/lib/python3.6/site-packages/brevitas_examples/bnn_pynq/trainer.py", line 140, in __init__
    self.model.load_state_dict(model_state_dict, strict=args.strict)
AttributeError: 'Trainer' object has no attribute 'model'`

I removed self and args.strict in trainer.py in if args.resume statement
`self.model.load_state_dict(model_state_dict, strict=args.strict)`
It helped but after that program just finished without any error, only the the message: Loading optimizer checkpoint

**Comment by volcacius** [comment]
Hello, 
Thanks for reporting the problem, yes "self" shouldn't be there, I'm going to commit a fix. 
If the program finishes it's because the training is over. When you resume from a checkpoint, it also resumes the number of epochs you have trained the checkpoint for. It's possible the checkpoint trained already for 10 epochs? If so, you should increase --epochs you are passing from the command line.

**Comment by anadb** [comment]
Thx, it is working
