### ISSUE TITLE
Possible to build Convolutional Autoencoder?

### ISSUE THREAD

**Issue by dustinjoe** [Xilinx/brevitas#164]
Hi. I am quite new to Pytorch have to admit. Just wondering if it is possible to build a quantized convolutional autoencoder model for tasks like CIFAR10?
I have found an example realization like this: [https://www.cs.toronto.edu/~lczhang/360/lec/w05/autoencoder.html](url)
 And seems that it needs ConvTranspose2d. I can see 1d in current brevitas here. Is it possible to build one with some alternative ways?
Thank you!

**Comment by Giuseppe5** [comment]
Considering how an autoencoder works, I think it would always require a ConvTranspose2d.
As of now, we do not have any plan for the implementation of that module. 
Everyone is free to try and implement new quantized module by themselves by taking the existing modules (Conv2d, ConvTranspose1d) as 'template', and me and @volcacius will be more than happy to review the PR and help with the development. It is not necessary to fully understand what brevitas is doing at every step in order to implement a new quantized layer.

It may happen also that one of us will work to implement that layer, but in that case there's no guarantee on the time, considering how many things we are working on at any given time.

Hope you'll understand.

**Comment by dustinjoe** [comment]
Thank you for your reply!
I think I am going to make some trials on FC based autoencoder first.
I will keep tracking on this exciting project. An official end-to-end workflow would really be a game changer for current hardware accelerator.
