### ISSUE TITLE
Two little questions

### ISSUE THREAD

**Issue by dustinjoe** [Xilinx/brevitas#233]
Hello, sorry interrupting. Two little questions:

1. Is there a way I can get an original floating point model for the BNN example CNV cifar10 model architecture? I want to make some performance comparisons on it with the quantized models?
2. Is there a performance estimation statistics tool inside that can show me the computation complexity of the model? For example in Google's qKeras their model summary return the number of MACs for a model? Guess this might be a useful reference for model design

Thank you!

**Comment by volcacius** [comment]
Hello,

1. You can disable quantization simply by setting weight/act_quant to None, and the layer will behave like its floating point variant. Because QuantIdentity in floating point is just an identity function though you would get a linear neural network, which is probably not what you want, so I'd replace it with a nn.ReLU. Also be careful that the current hyperparameters are tuned for training at very low precision, especially weight_decay = 0 is not something that you would want to do in floating point.

2. I don't think we have anything open source at the moment, but yeah it would make sense to have it there. I really need to make progresses on other stuff first though so it won't happen soon. In the meantime for MACs you can use any other existing tool like https://github.com/Swall0w/torchstat as long as it matches a layer based on `isinstance` (QuantConv2d inherits Conv2d so `isinstance(QuantConv2d(...), Conv2d) == True`). The number of MBs for model size will be wrong though since it doesn't take into account quantization.

Alessandro

**Comment by dustinjoe** [comment]
Thank you for your valuable suggestions!
I am going to make trials on these.
