### ISSUE TITLE
Optimizer with QuantTensor Error 

### ISSUE THREAD

**Issue by kim-sunghoon** [Xilinx/brevitas#27]
Hello, Thank you for awesome tool!! 
I'm working on combining DARTs [ICLR 2019] with the brevitas.
Then it seems like QuantTensor is not optimized by the various useful optimizer in torch (torch.optim.Adam or SGD and so on, plz see following error)

```shell
TypeError: optimizer can only optimize Tensors, but one of the params is brevitas.quant_tensor.QuantTensor
``` 

Is there a way to learn QuantTensor with the Optimizer?

and my code is: 
```python
44     net_crit = nn.CrossEntropyLoss().to(device)                                          
 45     model = SearchCNNController(C_in=input_channels,                                     
 46     ¦   ¦   ¦   ¦   ¦   ¦   ¦   C=config.init_channels,                                  
 47     ¦   ¦   ¦   ¦   ¦   ¦   ¦   n_classes=n_classes,                                     
 48     ¦   ¦   ¦   ¦   ¦   ¦   ¦   n_layers=config.layers,                                  
 49     ¦   ¦   ¦   ¦   ¦   ¦   ¦   criterion=net_crit,                                      
 50     ¦   ¦   ¦   ¦   ¦   ¦   ¦   n_nodes = config.n_nodes,                                
 51     ¦   ¦   ¦   ¦   ¦   ¦   ¦   device_ids=config.gpus,                                  
 52     ¦   ¦   ¦   ¦   ¦   ¦   ¦   imagenet_mode=config.dataset.lower() in utils.LARGE_DATAS    ETS,                                                                                     
 53     ¦   ¦   ¦   ¦   ¦   ¦   ¦   quant=config.quant)                                      
 54     model = model.to(device)                                                             
 55                                                                                          
 56     # weights optimizer                                                                  
 57     w_optim = torch.optim.SGD(model.weights(), config.w_lr, momentum=config.w_momentum,  
 58     ¦   ¦   ¦   ¦   ¦   ¦   ¦ weight_decay=config.w_weight_decay)                        
 59     # alphas optimizer                                                                   
 60     alpha_optim = torch.optim.Adam(model.alphas(), config.alpha_lr, betas=(0.5, 0.999),  
 61     ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦  weight_decay=config.alpha_weight_decay)              
```

**Comment by volcacius** [comment]
Hello,

QuantTensor is just a tuple to aggregate values (tensor, scale, bit_width) that are computed at runtime by a QuantLayer. It's not something that you learn directly, it's the output of a quantization module that depends on various learned parameters.

For example, if you look at how the forward pass of QuantConv2d is implemented, the submodule self.weight_quant(self.weight) returns a (quant_weight, quant_weight_scale, quant_weight_bit_width) tuple. Here the learned parameter is self.weight, as well as (depending how you configured your quantization) extra learned parameters inside weight_quant for scaling and bit width. Then quant_weight is used to compute the conv2d operation instead of self.weight.

In general, if you need to learn a quantized parameter, you declare  a standard torch.nn.Parameter together with a quantization module. Then at runtime, you pass the parameter through the quantization module, and then you use the output of the quantization module instead of the parameter for whatever operation you need. 
Brevitas provides WeightQuantizationProxy and ActivationQuantizationProxy as reference quantization modules, which are used respectively in like QuantConv2d and QuantReLU, but you can implement your own using the components in brevitas.core.

Alessandro
