### ISSUE TITLE
Question about weight_scaling_impl_type 

### ISSUE THREAD

**Issue by andylai0212** [Xilinx/brevitas#29]
Hi, thanks for awesome work!
Could you give a short explanation about the various strategies in weight_scaling_impl_type.
For example, "AFFINE_STATS","STATS","PARAMETER_FROM_STATS".

**Comment by volcacius** [comment]
Hello,

We are working on extending the documentation. In the mean time, the main difference is that STATS learns scaling as a statistical function of the full precision weights (backpropagating through it), while PARAMETER_FROM_STATS learns a separate parameter for scaling that is initialized based on those statistics. AFFINE_STATS is an attempt at mixing the two things, but they way it is currently implemented hasn't proven useful results so far (I have a new implementation that works better but haven't pushed it out yet). 
In general there isn't a single option that works best, it really depends on the topology and the overall training setting (task/loss/optimizer etc).

**Comment by andylai0212** [comment]
Thanks for your quick reply. I would like to quantize Lenet with 6-bit wieght and 4-bit activation. 
For the bias in conv layer, I want to quantize to 10-bit with scale factor equals to weight scale factor times activation scale factor. What parameter should I pass in the QuantConv2d ?

**Comment by volcacius** [comment]
First, you need to set `return_quant_tensor=True` in the activation layer before the conv layer, and then pass the QuantTensor you get from the activation as input to the conv layer forward. This is required so that bias can have the correct scale factor (as you mentioned).
To setup QuantConv2d, you can pass the following:

```
weight_quant_type = QuantType.INT
weight_bit_width = 6
bias_quant_type = QuantType.INT
bias_bit_width = 10
compute_output_scale = True 
compute_output_bit_width = True 
```
plus whatever option you want for scaling.

`compute_output_bit_width` is required at the moment, even though it's actually ignored since you are specifying manually 10 bits. I need to make it optional when bias_bit_width is specified.

Alessandro

**Comment by andylai0212** [comment]
Hi, I have tried to get start with the example code :
`
from torch.nn import Module
import torch.nn.functional as F
import brevitas.nn as qnn
from brevitas.core.quant import QuantType

class QuantLeNet(Module):
    def __init__(self):
        super(QuantLeNet, self).__init__()
        self.conv1 = qnn.QuantConv2d(3, 6, 5, 
                                     weight_quant_type=QuantType.INT, 
                                     weight_bit_width=8)
        self.relu1 = qnn.QuantReLU(quant_type=QuantType.INT, bit_width=8, max_val=6)
        self.conv2 = qnn.QuantConv2d(6, 16, 5, 
                                     weight_quant_type=QuantType.INT, 
                                     weight_bit_width=8)
        self.relu2 = qnn.QuantReLU(quant_type=QuantType.INT, bit_width=8, max_val=6)
        self.fc1   = qnn.QuantLinear(16*5*5, 120, bias=True, 
                                     weight_quant_type=QuantType.INT, 
                                     weight_bit_width=8)
        self.relu3 = qnn.QuantReLU(quant_type=QuantType.INT, bit_width=8, max_val=6)
        self.fc2   = qnn.QuantLinear(120, 84, bias=True, 
                                     weight_quant_type=QuantType.INT, 
                                     weight_bit_width=8)
        self.relu4 = qnn.QuantReLU(quant_type=QuantType.INT, bit_width=8, max_val=6)
        self.fc3   = qnn.QuantLinear(84, 10, bias=False, 
                                     weight_quant_type=QuantType.INT, 
                                     weight_bit_width=8)

    def forward(self, x):
        out = self.relu1(self.conv1(x))
        out = F.max_pool2d(out, 2)
        out = self.relu2(self.conv2(out))
        out = F.max_pool2d(out, 2)
        out = out.view(out.size(0), -1)
        out = self.relu3(self.fc1(out))
        out = self.relu4(self.fc2(out))
        out = self.fc3(out)
        return out

model = QuantLeNet()
`
and the RunTimeError occuors:
![image](https://user-images.githubusercontent.com/38522067/74226217-233c2a00-4cf7-11ea-80cc-aaa9eea135d8.png)
Could you give any advice,thanks?

**Comment by Giuseppe5** [comment]
We recently re-wrote all the functions that use the Straight-Throught Estimator. Although we tested everything, there are some hidden bugs (mainly due to some idiosyncrasies of Pytorch JIT) that may have slipped through, such as this one.

Try pull and install the latest version of Brevitas now, and everything should work just fine.

**Comment by andylai0212** [comment]
Thanks, it works :)

**Comment by andylai0212** [comment]
> First, you need to set `return_quant_tensor=True` in the activation layer before the conv layer, and then pass the QuantTensor you get from the activation as input to the conv layer forward. This is required so that bias can have the correct scale factor (as you mentioned).
> To setup QuantConv2d, you can pass the following:
> 
> ```
> weight_quant_type = QuantType.INT
> weight_bit_width = 6
> bias_quant_type = QuantType.INT
> bias_bit_width = 10
> compute_output_scale = True 
> compute_output_bit_width = True 
> ```
> 
> plus whatever option you want for scaling.
> 
> `compute_output_bit_width` is required at the moment, even though it's actually ignored since you are specifying manually 10 bits. I need to make it optional when bias_bit_width is specified.
> 
> Alessandro
I have few more questions:
1. How can I quantize input image to QuantTensor so I can pass it to the first QuantConv2d layer as its input?
2. There is a F.max_pool2d between  QuantRelu and QuantConv2d, so it raises a `TypeError: max_pool2d(): argument 'input' (position1) must be tensor, not QuantTensor`.

**Comment by volcacius** [comment]
1. The input image is probably already quantized. If we already talking about images, you probably have 8 bit values coming from a decoded jpeg in [0, 255] as input, that then the preprocessing normalize. What you want instead is to modify the preprocessing to have values in between [-128/128, 127/128], so that your scale factor is 1/128. This way then you can declare a QuantTensor as input to the first QuantConv2d, with tensor the input preprocess correctly, 1/128 the scale, 8 the number of bits.

2. Whenever you have an operation that doesn't support QuantTensor (and doesn't need to, like max pooling), you just apply only to the first element of the QuantTensor tuple. So you unpack the tuple (QuantTensor is just a named tuple) you apply your op, and then you repack it.

Alessandro

**Comment by andylai0212** [comment]
> * The input image is probably already quantized. If we already talking about images, you probably have 8 bit values coming from a decoded jpeg in [0, 255] as input, that then the preprocessing normalize. What you want instead is to modify the preprocessing to have values in between [-128/128, 127/128], so that your scale factor is 1/128. This way then you can declare a QuantTensor as input to the first QuantConv2d, with tensor the input preprocess correctly, 1/128 the scale, 8 the number of bits.
> *

Does that make sense to quantize the input to 4-bit rather than 8-bit, and learn the scale factor durning training?

**Comment by volcacius** [comment]
You can also do that. Just throw in a QuantHardTanh.
