### ISSUE TITLE
QuantCat Error

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#308]
Hello author, I set the return quant tensor to True, and set up self.quant_cat = QuantCat(). But an error occurred when executing this statement: out = self.quant_cat(x1,x2, dim=1)
error:
     raise RuntimeError("Computing zero point of output accumulator not supported yet.")

**Comment by volcacius** [comment]
Can you please report the full error? I think the issue is somewhere else.

**Comment by YZW-explorer** [comment]
Thank you so much！
out = self.quant_cat((self.branch1(x), self.branch2(x)), dim=1)
 File "/torch/nn/modules/module.py", line 723, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/torch/nn/modules/module.py", line 723, in _call_impl
    result = self.forward(*input, **kwargs)
  File "python3.8/site-packages/brevitas/nn/quant_conv.py", line 224, in forward
    return self.forward_impl(input)
  File "python3.8/site-packages/brevitas/nn/quant_layer.py", line 381, in forward_impl
    raise RuntimeError("Computing zero point of output accumulator not supported ye

**Comment by volcacius** [comment]
The issue is not with the cat layer, it's with a convolution inside one of the branches. As the error says, at the moment computing a zero-point != 0 of an output accumulator in not supported yet. Alternatives are:
- set return_quant_tensor=False on that layer.
- set an output_quant quantizer on that layer.
- change the input/weight quantization so that the zero-point of both input and weight is zero, and the output zero point then becomes zero.

**Comment by YZW-explorer** [comment]
Thank you so much！
