### ISSUE TITLE
How I can get the scale

### ISSUE THREAD

**Issue by YZW-explorer** [Xilinx/brevitas#309]
Dear author, I would like to ask how I can get the scale calculated in the Quantization - Aware Training using Brevitas if I save the model as a PTH file by using torch. save( )

**Comment by volcacius** [comment]
It won't appear directly in the .pth since it's not necessarely a 1:1 mapping to a single torch.nn.Parameter. You have two options:

- At runtime you can invoke a method to retrieve it and then save it separately:
  - For a layer like QuantConv2d you can do QuantConv2d.quant_weight_scale() for the weight scale
  - For a layer like QuantReLU you can QuantReLU.quant_act_scale() for the activation scale

- To get a file that contains all the information you need, I merged this week experimental support for generating a custom 'generic' ONNX based representation. For example, to invoke it on one of the pretrained imagenet examples:

```python

from brevitas.export.onnx.generic.manager import BrevitasONNXManager
from brevitas_examples.imagenet_classification import quant_proxylessnas_mobile14_4b5b

BrevitasONNXManager.export(quant_proxylessnas_mobile14_4b5b(pretrained=True), input_t=torch.randn(1, 3, 224, 224), export_path='./quant_proxylessnas.onnx')
```
If you look at it in Netron it looks like this:
![screenshot](https://user-images.githubusercontent.com/1934033/117314295-84ad6300-ae7e-11eb-8b4b-12bd0c1dab94.PNG)

You have custom Quant nodes where the inputs are as follow:
- 0 is the tensor to quantize (weights or activations)
- 1 is the scale
- 2 is the zero-point
- 3 is the number of bits

It's new, let me know how it works for you.

**Comment by YZW-explorer** [comment]
My goodness, thank you so much!!! I think I will try them all, and I will continue to discuss with you when I have news.
               To my most sincere thanks!

**Comment by YZW-explorer** [comment]
Hello author, I tried it after imitating your code.
I obtained the weight of a convolutional layer from the downloaded pretrained pth file:
![image](https://user-images.githubusercontent.com/74363764/119212808-5a4ddd80-baed-11eb-8921-d2dabe7b1f1a.png)
Then I got the scale of the corresponding layer from the onnx file(The reason I did this is that I want to use pytorch to imitate the quantization and dequantization process in brevitas. But I found that the scale is too small.):
![image](https://user-images.githubusercontent.com/74363764/119212855-a7ca4a80-baed-11eb-80a6-eb3c7c70866c.png)
I save them as npy file:
![image](https://user-images.githubusercontent.com/74363764/119212867-bdd80b00-baed-11eb-926d-e73ff093d5e6.png)
I wrote a simple code to simulate the quantification process of weights.
![image](https://user-images.githubusercontent.com/74363764/119212922-26bf8300-baee-11eb-86df-c9b99e511d97.png)
The quantified weights are all 0. I was shocked.
![image](https://user-images.githubusercontent.com/74363764/119212937-3dfe7080-baee-11eb-97ad-04028edc2f72.png)
