### ISSUE TITLE
still need of example of quantized network with BN 

### ISSUE THREAD

**Issue by lovodkin93** [Xilinx/brevitas#368]
following issue #363,
I have tried to do what you suggested,
but I am a bit confused as to how to do it.
My confusion stems from the fact that after training a quantized model, how can I update its parameters to be `return_quant_tensor=True`?
Also, when trying to fuse the models, using the following command:
```
from torch.quantization import fuse_modules
model_ResNet50 = fuse_modules(model_ResNet50, [['conv1', 'bn1', 'relu'], 
                                                ['layer1.conv2', 'layer1.bn2', 'layer1.relu'], ['layer1.conv3', 'layer1.bn3'], 
                                                ['layer2.conv2', 'layer2.bn2', 'layer2.relu'], ['layer2.conv3', 'layer2.bn3'],
                                                ['layer3.conv2', 'layer3.bn2', 'layer3.relu'], ['layer3.conv3', 'layer3.bn3'],
                                                ['layer4.conv2', 'layer4.bn2', 'layer4.relu'], ['layer4.conv3', 'layer4.bn3']])
```
I got the following error:
```
NotImplementedError: Cannot fuse modules: (<class 'brevitas.nn.quant_conv.QuantConv2d'>, <class 'torch.nn.modules.batchnorm.BatchNorm2d'>, <class 'torch.nn.modules.activation.ReLU'>)
```

So I am confused as to how to fuse a `QuantConv` layer with a `BatchNorm` layer.
Thanks!

**Comment by volcacius** [comment]
Hello,

You are trying to fuse together Conv + BN + ReLU using quantization utilities from PyTorch. Brevitas is a completely separate quantization library that does not have anything to do with upstream support for quantization in PyTorch, and it doesn't support that kind of pattern. What I suggested is to merge BN into the Conv weights. You can do it e.g. with this function https://github.com/Xilinx/brevitas/blob/a5bfd6dc5e030f0047ac1ee47932b60e8e873e17/src/brevitas/nn/utils.py#L61 . 
Also, consider using PyTorch upstream support for quantization, rather than Brevitas, if you think it might fit your needs better.
