### ISSUE TITLE
Cite to quantization techniques in `QuantIdentity(bit_width=8)` and `QuantReLU(bit_width=8)`.

### ISSUE THREAD

**Issue by ninfueng** [Xilinx/brevitas#370]
Hello,

I would like to cite to quantization techniques in `QuantIdentity(bit_width=8)` and `QuantReLU(bit_width=8)`.
In both, the zero points are zero. So I think the quantization techniques are based on [TQT](https://arxiv.org/abs/1903.08066)? Is that correct?

Thank you. I will also cite `brevitas` in my work.

**Comment by volcacius** [comment]
Hello,

Thanks for reaching out. Yes that's the general technique, i.e. having the scale a learned parameter, although that particular paper is specific to power-of-two scale factors, while in the default case QuantIdentity/QuantReLU do floating-point scale factors. 
The other difference is that in order to initialize the learned scale factor the quantizer takes a moving average of the 99.99 percentile of the activations for a certain number of iterations, while that paper does KL minimization.
