### ISSUE TITLE
quantize output of conv layer

### ISSUE THREAD

**Issue by linbaiwpi** [Xilinx/brevitas#43]
hello, for FPGA implementation, we need the output of convolution layer to be fixed point.

I notice that at Line 115 and 116 of "brevitas/nn/quant_conv.py", two parameters of QConv2D: **compute_output_scale** and **compute_output_bit_width**.
So can I tune these two parameters to quantize the output of conv layer?

**Comment by andylai0212** [comment]
Same question here. Can I restrict output bit-width to user-define number for inference in hardware?

**Comment by volcacius** [comment]
Hello,

Output bit width and scale factor depends on input bit width and scale factor, the weights' bit width and scale factor, and the size of the layer. They are relevant for example to assess the worst-case size of an accumulator in hardware, or to perform bias quantization.
If you want to requantize the output of a layer, you can insert  a quantized activation function such as QuantReLU (for unsigned values) or QuantHardTanh(for signed values). Both of them rescales the output with a new scaling factor. 

Alessandro

**Comment by andylai0212** [comment]
Hi,thanks for reply. In my situation, the accumulator in hardware has restricted bitwise, which may lead to overflow. Thus, can I simulate the accumulator with restricted bitwise durning training?

**Comment by volcacius** [comment]
Can you please define what you mean with restricted bitwise?

**Comment by andylai0212** [comment]
For example, In hardware, weights and activations are 8 bit. However, accumulator is only 16 bit. This may lead to overflow if I directly use the trained weight.

**Comment by volcacius** [comment]
I see what you mean. You can use ClampQuantAccumulator, with min_overall_bit_width=16 and max_overall_bit_width=16, but the problem is that it works properly only for accumulation after element-wise operations (for example, the residual add of a resnet architecture). 
Modelling the size of an accumulator of an operation like conv2d requires to re-implement conv2d without cudnn and with custom accumulation at CUDA level, which is not supported in Brevitas. 
The way I would do it would be to use im2col to turn conv2d into a GEMM, and then extend Nvidia's CUTLASS (an open source high performance GEMM implementation) to clamp the accumulator after every MAC operation. I might do it in the long term, but it takes time and at the moment it's not high in my priority list. If you want to contribute it, I would be happy to accept a pull request.

Alessandro

**Comment by vdgs** [comment]
@andylai0212 Did you adapt this quantization framework to your hardware successfully?
