### ISSUE TITLE
why the scale of bias not in fixedpoint format ?

### ISSUE THREAD

**Issue by YingXiangLi10** [Xilinx/brevitas#515]
Hello, I've been training a model with fixedpoint scale, and since the scale of bias should be input_scale*weight_scale, they aren't perfectly equal? Just like the one below.

The input quant is **Int8ActPerTensorFixedPoint**, the weight quant is **Int8WeightPerTensorFixedPoint**, the bias quant is **Int16Bias**.
![Screenshot from 2023-01-23 02-07-25](https://user-images.githubusercontent.com/48464941/213932443-fbe554c5-0395-4910-864e-287220286fbf.png)
![Screenshot from 2023-01-23 02-16-13](https://user-images.githubusercontent.com/48464941/213932804-c1748040-7090-4b54-a171-d913afd783af.png)

The input scale is 0.0078125(2^-7), the weight scale is 0.00390625(2^-8), so the bias scale should be 2^(-7) * 2(-8) = 0.000030518, but the value export is 0.000030517578125. The numbers are close, but they are not perfectly the same. Is it because of the imprecise float calculation in python? 

Besides, I've also noticed that the export bias isn't integral multiple of its scale, for example, -0.02718665823340416 / 0.000030517578125 = −890.852416992. And I use **export_brevitas_onnx** to export the model.

The model works fine when I manually rounded the biases, it has no impact on the result. But I still want to know if it matters.

**Comment by Giuseppe5** [comment]
Hello,
Thanks for the issue!

Regarding the first question, if I run in python:
```python
2**(-7) * 2**(-8)
```
I get `3.0517578125e-05`, which is the exported value. Am I missing something?

About the second question, what you see makes sense because the Quant node has to be computed, meaning that the input bias value has to be divided by scale factor, rounded and clipped. As you pointed out, there should not be any impact on the result because this is the expected flow.

Let me know if there are any more questions I could help you with, or if something is not clear.

**Comment by YingXiangLi10** [comment]
Thanks for your answer!!
For the first question, I should test it using python by myself, so I can figure out the reason.
For the second question, I notice that the exported weight is rounded, not like the bias.

![Screenshot from 2023-01-23 20-29-22](https://user-images.githubusercontent.com/48464941/214039903-1f36b43f-b0f3-4cde-b9d4-3694c4fd574d.png)
![Screenshot from 2023-01-23 20-23-27](https://user-images.githubusercontent.com/48464941/214038762-703b47ee-dbb8-4fb3-8d3d-b7ecdba977d9.png)

-0.0546875÷0.0078125 =-7, so what is the difference between weight and bias when exporting? I also notice that the weight's narrow attribute is 1, while bias' is 0. So does this have something to do with **"narrow attribute"**, and how can I set the narrow attribute correctly?

**Comment by Giuseppe5** [comment]
Yes the weight are already rounded as an optimization.

Narrow refers to narrow_range attribute, which means that you have symmetrical representation of positive and negative values after quantization (for example, for signed 8b quantization, with narrow_range enabled your integer range would be between -127/127 instead of -128/127).

If this is not the behavior you desire, you can add another flag to your weight quantizer specifying `weight_narrow_range=False`. However it has no impact on this particular aspect of the export.

**Comment by YingXiangLi10** [comment]
Thank you very much! Now I know what the "narrow" means.
