### ISSUE TITLE
Some question about how to inference on real INT8 weight

### ISSUE THREAD

**Issue by zero90169** [Xilinx/brevitas#61]
Hi there,
First, I have trained a net and I know that I can access the real INT8 weight of model by using property _int_weight_ and _quant_weight_scale_ to extract the integer weights and their scale factor, activations have method _quant_act_scale()_ to extract the scale factor.
However, I have no idea how to use it to do real INT8 inference.
Can anyone give me a toy example how to use those parameters to do inference?

**Comment by volcacius** [comment]
Hello,

Brevitas is a library for research on quantization aware training. How to perform inference is out of its scope, especially because it depends on your target hardware/platform. If you are interest in dataflow-style inference on Xilinx FPGAs, please checkout the progress being made over at [https://github.com/Xilinx/finn](https://github.com/Xilinx/finn) to deploy Brevitas trained models.

Alessandro
