### ISSUE TITLE
Replacing Layers from pre-trained model with quantized Brevitas layers

### ISSUE THREAD

**Issue by g12bftd** [Xilinx/brevitas#614]
Is there a simple way to take a pre-trained model (e.g YOLO, BERT etc) and replace any Conv/Linear layers with QuantConv/QuantLinear? Perhaps with setattr? 

Thanks

**Comment by Giuseppe5** [comment]
Hi,
Thanks for your question!

As a matter of fact, we have recently expanded and simplified the process you just described, to go from a generic floating point model to one with Quantized Layers.

[In this folder](https://github.com/Xilinx/brevitas/tree/dev/src/brevitas_examples/imagenet_classification/ptq) you can find a detailed explanation and examples of how to use our `ptq_evaluate.py` script to go from a generic torchvision model to its quantized counterpart.
An important thing to mention is that the script is mostly aimed for post-training quantization, but nothing prevents you from following all the steps up to the point where a quant_model is generated, and then use that in a quantization-aware training setting.


You could start from that script and modify it for other models that are not necessarily taken from torchvision. It must be noted however that we leverage Torch FX for our pre-process and quantization transformation (when targetting `generic` backened, while it is not needed anymore for the `layerwise` backend).
Otherwise, if you use the `dev` branch and the `layerwise_quantize` function without calling `preprocess_for_quantize`, you should be able to automatically replace all the layers that you mentioned with their quantized counterparts without using Torch FX.

You can customize the quantization configuration for each type of layer by adapting the dictionaries that are passed to the quantization functions.

If you need further help, feel free to let us know :)

**Comment by Giuseppe5** [comment]
Closing this issue, please re-open in case you need further assistance with this matter.

Best,
Giuseppe
