### ISSUE TITLE
Unsigned Quantization

### ISSUE THREAD

**Issue by mahdi259** [Xilinx/brevitas#876]
Hi
Is there any way to specify **unsigned** quantization in QuantIdentity or QuantLinear?
Thanks

**Comment by capnramses** [comment]
Hi @mahdi259 
I think for `QuantIdentity` the answer is just to use `Uint8ActPerTensorFloat` when initialising `QuantIdentity` with optional argument `act_quant=Uint8ActPerTensorFloat` instead of the default int8 - which you can see here https://github.com/Xilinx/brevitas/blob/200456825f3b4b8db414f2b25b64311f82d3991a/src/brevitas/nn/quant_activation.py#L106

For weights in e.g. `QuantLinear` I think it would be less common to use unsigned integes, so I don't think there's a datatype available built-in, but you could experiment with that by extending the `Int8` weight data type https://github.com/Xilinx/brevitas/blob/200456825f3b4b8db414f2b25b64311f82d3991a/src/brevitas/quant/fixed_point.py#L24

I hope that helps!

**Comment by mahdi259** [comment]
Thanks That's it. One more question. I have read ULPPACK paper that performs inner product of unsigned numbers, i.e. unsigned inputs and weights. I agree that it's odd to have unsigned weights. Do you know how they use ULPPACK in networks like ResNet? 
Thanks

**Comment by capnramses** [comment]
I haven't read that paper I'm sorry! I think that might be off topic for the repo, so I'm going to close this Issue.
