### ISSUE TITLE
Inference time dynamic quantization

### ISSUE THREAD

**Issue by volcacius** [Xilinx/brevitas#88]
Track discussions around dynamic quantization, in the sense of performing actual integer based inference. Scope is to still fit within standard(ish) pytorch APIs, possibly leveraging any of their own quantization backends (where possible).

**Comment by Giuseppe5** [comment]
In current implementation, only INT quantization type is supported (no BINARY and TERNARY).
To enable Dynamic Quant, the enviromental flag BREVITAS_USE_DYNAMIC_QUANT must be set to true.

The "return_quant_tensor" flag for every layer and activation is override by the dynamic quant flag.

For convolutional or linear layers, when using dynamic quantization, the integer weights are computed once for the first batch, and then stored. If the input is a QuantTensor, the convolutions is executed between integer tensors, otherwise weights are re-casted to floating points. The output tensor is in floating point in any case.

For activations, the input tensor should be in floating point, and the output tensor will be in floating point as well.

**Comment by YouanLi** [comment]
Is that means, brevitas can support fixed-point inference.

**Comment by volcacius** [comment]
This is going to be supported by 'exporting' to pytorch quantized functional. Closing.
