### ISSUE TITLE
List of all the avalable quantization strategies

### ISSUE THREAD

**Issue by balditommaso** [Xilinx/brevitas#978]
Hi,

First of all congratulation for the amazing work that you have done so far re-implementing all the Tensor operations in the quantized domain. I saw that the documentation is still under development, but I wonder if there is a place where are listed all the avalable quantization strategies combination with the relative parameters.

Kind regards,

Tom

**Comment by Giuseppe5** [comment]
Hi,

Thank you for your comment :)
Yes documentation is WIP, but in terms of quantization strategies, it would be easier if you would let us know what you're interested in, rather than we listing everything.

Brevitas is designed to be highly modular and it is possible to combine lots of different quantization options. For example, you can quantize your weight per-channel with asymmetric quantization, using different statistics to compute the scale or the zero point; you can restrict the scale value only for weights but not activations. You can pick two completely different quantization strategies for weights and activations, etc. etc.

We offer some pre-packaged quantization options [here ](https://github.com/Xilinx/brevitas/tree/master/src/brevitas/quant) based on common use cases, but it is definitely not an exhaustive list.

**Comment by balditommaso** [comment]
Right, 

I saw that there are many pre-built quantization strategies that we can take as example, but I would like to test some custom combinations. For instance, it's not clear to me how to set up an asymmetric quantization startegy for the activation layers and the available STATS.Op to exclude outliers from the scale computation?

OT:  I am testing a quantized version of a custom layer that I have made and I wonder what `per_elem_ops` should return. I thought it was the number of operations accomplished by each layer, but looking at other quantized layers it looks something different.

**Comment by Giuseppe5** [comment]
[This](https://github.com/Xilinx/brevitas/blob/200456825f3b4b8db414f2b25b64311f82d3991a/src/brevitas/quant/shifted_scaled_int.py#L52) will already do asymmetric per tensor activation quantization with percentile for excluding outlier. Percentiles are set [here](https://github.com/Xilinx/brevitas/blob/200456825f3b4b8db414f2b25b64311f82d3991a/src/brevitas/quant/base.py#L145), but you could simply inherit the quantizer and change the percentiles like the following:
```python
class MyActQuant(ShiftedUint8ActPerTensorFloat):
    high_percentile_q = new_high_value
    low_percentile_q = new_low_value

```

I believe you can ignore per_elem_ops, it is not actively used during quantization, but I'll come back to you on that with more info.
