### ISSUE TITLE
Assign scale value for QuantIdentity()

### ISSUE THREAD

**Issue by ONQLin** [Xilinx/brevitas#984]
Hi,

I see that we can apply RestrictValueType.* for the weights of QuantLinear() and etc, which constrain the scale values.

So I just wonder is it possible to restrict or assign constant scale value for QuantIdentity() in training mode? I have tried to apply same attribute or set "scaling_impl_type". But both failed.

Best Regards

**Comment by GiulioMa** [comment]
I am facing a similar issue in my project. I am designing a model that operates with integers, but its output needs to be converted to a float so I can apply the tanh function.

My goal is for my FPGA implementation to produce results comparable to Brevitas. To achieve this, I extract the integer weights and the scale of the last layer from Brevitas. Then, I send this data to the FPGA, which uses the weights for inference and the scale to convert the output back to a float.

The problem is that Brevitas keeps changing the output scale, and I have only been able to fix this by introducing my own quantizer.

Is there a better way to handle this issue?
